# Generated by Django 5.2.15 on 2026-06-24 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='company_type',
            field=models.CharField(blank=True, help_text='Restaurant, Hôtel, Grossiste, Coopérative, Supermarché...', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('producer', 'Producteur'), ('supplier', 'Fournisseur'), ('buyer', 'Acheteur'), ('transporter', 'Transporteur'), ('collector', 'Collecteur de prix'), ('admin', 'Administrateur')], default='buyer', max_length=24),
        ),
    ]
