# Generated by Django 5.2.15 on 2026-06-24 11:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('city', models.CharField(max_length=120)),
                ('province', models.CharField(max_length=120)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
            ],
            options={
                'ordering': ['province', 'city', 'name'],
                'indexes': [models.Index(fields=['province', 'city'], name='prices_mark_provinc_4e3ac5_idx')],
                'unique_together': {('name', 'city', 'province')},
            },
        ),
        migrations.CreateModel(
            name='PriceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='CDF', max_length=8)),
                ('unit', models.CharField(default='kg', max_length=16)),
                ('recorded_at', models.DateField()),
                ('source', models.CharField(blank=True, max_length=160)),
                ('is_validated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_records', to='prices.market')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='price_records', to='catalog.product')),
            ],
            options={
                'ordering': ['-recorded_at', 'product__name'],
                'indexes': [models.Index(fields=['product', 'recorded_at'], name='prices_pric_product_a337c9_idx'), models.Index(fields=['market', 'recorded_at'], name='prices_pric_market__55496f_idx'), models.Index(fields=['is_validated', 'recorded_at'], name='prices_pric_is_vali_59d6ed_idx')],
                'constraints': [models.UniqueConstraint(fields=('product', 'market', 'unit', 'recorded_at'), name='unique_daily_market_price')],
            },
        ),
    ]
