# Generated by Django 5.2.15 on 2026-06-24 14:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('marketplace', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit', models.CharField(default='kg', max_length=16)),
                ('target_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='CDF', max_length=8)),
                ('city', models.CharField(max_length=120)),
                ('province', models.CharField(max_length=120)),
                ('needed_before', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Ouverte'), ('matched', 'Correspondance trouvée'), ('closed', 'Fermée')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_requests', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_requests', to='catalog.product')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='marketplace_status_99144d_idx'), models.Index(fields=['product'], name='marketplace_product_24baa2_idx'), models.Index(fields=['province', 'city'], name='marketplace_provinc_eafcb8_idx'), models.Index(fields=['target_price'], name='marketplace_target__a3b01b_idx')],
            },
        ),
    ]
