# Generated by Django 5.2.15 on 2026-06-26 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_user_id_8a7c6b_idx',
            old_name='notificatio_user_id_8b0b0d_idx',
        ),
    ]
